### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by jeremylow** [PhillyDSA/pyactionnetwork#5]
## Expected Behavior

Instead of just returning the json response from the API, might be good to parse that response into classes for easier manipulation/access.

## Current Behavior

Just returns the json response from all API endpoints.

## Your Environment

* Version used (if applicable): 0.10.0

**Comment by otakup0pe** [comment]
I might be willing to take this on... Would there be a desire to retain backwards compatibility, or would a major (breaking) version bump be sufficient...

**Comment by jeremylow** [comment]
I'm not involved in the project much anymore since I've left the organization that used this. That said, I'm happy to keep development going by helping where I can.

It's pre-alpha software, so breaking changes are fine by me.
